method:
  # name: 2010to2019_altivalid
  name: alti_renoise
  
  # checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-23/glorys12_0init_0125_2010to2019_altivalid-21-01-54/glorys12_0init_0125_2010to2019_altivalid/checkpoints/best.ckpt
  checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-08-06/altivali_renoise-17-25-49/glorys12_0init_0125_2010to2019_altivalid/checkpoints/best.ckpt

  config:  /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-08-06/altivali_renoise-17-25-49/.hydra/config.yaml

  input_data: /Odyssey/public/data_challenge_ssh_ose/data/alongtrack/gridded_obs_sla_0.125.nc
  input_var: sla_filtered
  output_var: sla
  mask_path: /Odyssey/public/data_challenge_ssh_ose/data/sad/land_water_mask_8.nc

  # # ----------------------- glorys12 infer
  # input_data: /Odyssey/public/glorys/reanalysis/glorys12_2020_daily_sla_8th_input.nc
  # input_var: sla
  # output_var: sla
  # mask_path: /Odyssey/public/data_challenge_ssh_ose/data/sad/land_water_mask_8.nc

dims:
  # 1/4° global ---------------------------------------------------------------
  # patch: 15-648-1488
  # stride: 1-200-200
  # res: .25

  # 1/8° global ---------------------------------------------------------------
  patch: 15-656-608
  stride: 1-640-592
  res: .125

  # 1/8° global infer glorys12 ------------------------------------------------
  # patch: 15-96-96
  # stride: 1-80-80
  # res: .125
