method:
  # name: 2010to2019_altivalid
  # name: on2014altivali 
  # name: 2010to2019
  name: modelDaniel
  
  # checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-23/glorys12_0init_0125_2010to2019_altivalid-21-01-54/glorys12_0init_0125_2010to2019_altivalid/checkpoints/best.ckpt
  # checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-23/glorys12_0init_0125_only2014_altivali-11-17-16/glorys12_0init_0125_only2014_altivali/checkpoints/best.ckpt
  # checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-22/glorys12_0init_0125_2010to2019-23-46-56/glorys12_0init_0125_2010to2019/checkpoints/best.ckpt
  checkpoint: /Odyssey/public/_transit_zone_/model_0.125deg/val_mse_4.07106_epo_264.ckpt

  config: /Odyssey/public/_transit_zone_/model_0.125deg/config.yaml

  input_data: /Odyssey/public/data_challenge_ssh_ose/data/alongtrack/gridded_obs_sla_0.125.nc
  input_var: sla_filtered
  output_var: sla
  mask_path: /Odyssey/public/data_challenge_ssh_ose/data/sad/land_water_mask_8.nc

dims:
  # 1/4° global ---------------------------------------------------------------
  # patch: 15-648-1488
  # stride: 1-200-200
  # res: .25

  # 1/8° global ---------------------------------------------------------------
  patch: 15-656-608
  stride: 1-640-592
  res: .125
