method:
  # -------------------------------------------------------------------
  # SLA
  # -------------------------------------------------------------------
  # name: 2010to2019_altivalid
  name: 2010to2019
  # checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-23/glorys12_0init_0125_2010to2019_altivalid-21-01-54/glorys12_0init_0125_2010to2019_altivalid/checkpoints/best.ckpt
  checkpoint: /Odyssey/private/j25lee/4dvarnet-global-mapping/outputs/2025-07-30/glorys12_0init_0125_2010to2019-10-47-44/glorys12_0init_0125_2010to2019/checkpoints/best.ckpt

  config: ../config/xp/inference-glo12-sla.yaml

  input_data: /Odyssey/public/data_challenge_ssh_ose/data/alongtrack/gridded_obs_sla_0.125.nc
  input_var: sla_filtered
  output_var: sla
  geo_uv: false

dims:
  # patch: 15-648-1488
  # stride: 1-200-200
  # res: .25
  
  # 1/8° global ---------------------------------------------------------------
  patch: 15-656-608
  stride: 1-640-592
  res: .125
